### PR TITLE
[196] Conquest Hold Legionnaire

### PR DESCRIPTION
**Pull request by Rushor**
* Apply Movement

### CODE REVIEW

**Comment by Grz3s** [comment]
hey @Rushor 
Thank you for your work,,
They are some problems with this pull:
1st - `wpguid` was removed from creature_movemet (cmangos devs planing to remove more fields from there)
so we trying to stick with this:
INSERT INTO creature_movement (id, point, position_x, position_y, position_z, waittime, script_id, orientation, model1, model2) VALUES
2nd - you dont need to add every single sniffed "point" - I'm usualy keeping ones, which changes his xyz,,
3rd - he/she should walk in pair with another 'Conquest Hold Legionnaire'

**Comment by Rushor** [comment]
okay i will try to modify this tool - and yeah didn't found the other guy :D 
thx for the feedback, more inc

**Comment by Grz3s** [comment]
@Rushor can you pls ..say what email should i use ...if i want to 'do' your authorship on github? - for adding your stuff... koz i see you made some good new scripts:)

**Comment by Rushor** [comment]
well it's SBienati@web.de 
 - i will do some more work soon, but currently lk-hc-release on my server is starting soon, so much work incoming :(
with the 2 updates the movement for the eastern part of grizzlyhills is done

**Comment by xfurry** [comment]
@Grz3s you can find this info in his commit:

```
From c0ccbb71af45c76b15bea5c87e9241cdc7c4b953 Mon Sep 17 00:00:00 2001
From: Rushor <PBienati@web.de>
Date: Mon, 11 May 2015 22:25:55 +0200
Subject: [PATCH] [196] Conquest Hold Legionnaire
```

**Pull request closed without merging**
