### PR TITLE
[5xx] Fix Nerub'ar Victim

### PR DESCRIPTION
**Pull request by Phatcat**
Nerub'ar Victim currently moves around and melees you.

### CODE REVIEW

**Comment by Grz3s** [comment]
this doesn't work for WoTlK
need diff solution for these...

**Comment by Phatcat** [comment]
It doesn't work yet you're right. I am working on the core support for this.

**Comment by Phatcat** [comment]
It should make no difference to use = 510 or = 0x200 (which is what I done on my classic commits)

**Comment by Phatcat** [comment]
No wait that's right, it already had this flag this one. Nevermind about it, then ^^ Core support incoming soon.

**Pull request closed without merging**
